-- DATA VALIDATION QUERIES --


USE PROJECT;

SELECT COUNT(*) FROM drivers;
SELECT COUNT(*) FROM trucks;
SELECT COUNT(*) FROM loads;
SELECT COUNT(*) FROM trips;
SELECT COUNT(*) FROM fuel_purchases;
SELECT COUNT(*) FROM delivery_events;

-- These queries confirm that all the records are present and helps validate that no data was lost during import.


SELECT *
FROM trips t
WHERE NOT EXISTS (
    SELECT 1
    FROM loads l
    WHERE l.load_id = t.load_id
);
-- This query finds trips that do not have a matching load record, which helps identify broken relationships or data quality issues.


SELECT *
FROM fuel_purchases fp
WHERE NOT EXISTS (
    SELECT 1
    FROM trips t
    WHERE t.trip_id = fp.trip_id
);
-- checks for fuel transactions that are not linked to any trip, which may indicate incomplete or incorrect data.



-- DATA CLEANING QUERIES --

UPDATE loads
SET revenue = 0
WHERE revenue IS NULL;

-- handles missing revenue values to ensure accurate aggregation and prevent errors during financial analysis.


SELECT *
FROM loads
WHERE load_status = 'Cancelled';

-- This query identifies cancelled loads so they can be excluded from performance and revenue analysis without deleting the data.


-- ANALYSIS QUERIES --

SELECT 
    d.driver_id,
    d.first_name,
    d.last_name,
    COUNT(t.trip_id) AS total_trips
FROM drivers d
JOIN trips t
    ON d.driver_id = t.driver_id
GROUP BY d.driver_id, d.first_name, d.last_name
ORDER BY total_trips DESC;

-- This query measures driver workload by counting how many trips each driver has completed.


SELECT COUNT(*) AS total_trips
FROM trips;

-- This shows the total number of trips


SELECT 
    t.driver_id,
    SUM(l.revenue) AS total_revenue
FROM trips t
JOIN loads l
    ON t.load_id = l.load_id
GROUP BY t.driver_id
ORDER BY total_revenue DESC;
 
 -- This query evaluates driver contribution by summing the revenue from all loads handled by each driver.

 SELECT 
    SUM(revenue) AS total_revenue
FROM loads
WHERE load_status <> 'Cancelled';

--This query give total revenue generated by all the drivers

select count(driver_id) as total_drivers
from drivers;


 SELECT 
    trip_id,
    SUM(total_cost) AS fuel_cost
FROM fuel_purchases
GROUP BY trip_id;

-- This query calculates the total fuel cost for each trip by aggregating individual fuel purchase transactions.


SELECT 
    t.trip_id,
    l.revenue,
    fc.fuel_cost,
    (l.revenue - fc.fuel_cost) AS revenue_after_fuel
FROM trips t
JOIN loads l
    ON t.load_id = l.load_id
JOIN (
    SELECT trip_id, SUM(total_cost) AS fuel_cost
    FROM fuel_purchases
    GROUP BY trip_id
) fc
    ON t.trip_id = fc.trip_id;

    -- This query combines trip revenue with fuel costs to estimate profitability after fuel expenses using a subquery.




    SELECT 
    trip_id,
    average_mpg,
    CASE
        WHEN average_mpg >= 8 THEN 'High Efficiency'
        WHEN average_mpg BETWEEN 5 AND 7.99 THEN 'Medium Efficiency'
        ELSE 'Low Efficiency'
    END AS mpg_category
FROM trips;

-- This query classifies trips into fuel efficiency categories to make performance comparison easier for business users.


SELECT 
    AVG(fuel_cost) AS avg_fuel_cost_per_trip
FROM (
    SELECT 
        trip_id,
        SUM(total_cost) AS fuel_cost
    FROM fuel_purchases
    GROUP BY trip_id
) t;

-- shows average fuel cost per trip


SELECT
    event_id,
    scheduled_datetime,
    actual_datetime,
    CASE
        WHEN actual_datetime <= scheduled_datetime THEN 'On Time'
        ELSE 'Late'
    END AS delivery_status
FROM delivery_events
WHERE event_type = 'Delivery';

-- This query evaluates delivery punctuality by comparing scheduled and actual delivery times.


SELECT
    driver_id,
    total_revenue,
    RANK() OVER (ORDER BY total_revenue DESC) AS revenue_rank
FROM (
    SELECT 
        t.driver_id,
        SUM(l.revenue) AS total_revenue
    FROM trips t
    JOIN loads l
        ON t.load_id = l.load_id
    GROUP BY t.driver_id
)x;

-- This query ranks drivers based on the total revenue they generated, allowing easy identification of top performers.


SELECT *
FROM (
    SELECT
        d.home_terminal,
        d.driver_id,
        SUM(l.revenue) AS total_revenue,
        ROW_NUMBER() OVER (
            PARTITION BY d.home_terminal
            ORDER BY SUM(l.revenue) DESC
        ) AS rn
    FROM drivers d
    JOIN trips t ON d.driver_id = t.driver_id
    JOIN loads l ON t.load_id = l.load_id
    GROUP BY d.home_terminal, d.driver_id
) ranked
WHERE rn = 1;

-- This query finds the highest-revenue driver within each terminal using a window function for fair comparison.

SELECT TOP 6
    route_id,
    SUM(revenue) AS total_revenue
FROM loads
GROUP BY route_id
ORDER BY total_revenue DESC;

-- Top 6 Routes by Revenue



SELECT
    load_date,
    SUM(revenue) AS daily_revenue,
    SUM(SUM(revenue)) OVER (
        ORDER BY load_date
    ) AS running_revenue
FROM loads
GROUP BY load_date
ORDER BY load_date;

-- This query shows how total revenue accumulates over time, helping analyze growth trends.


